name: Build libsoundio for Windows/Mac/Linux

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies for MXE
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake autopoint bash bison bzip2 build-essential \
          cmake git libtool libltdl-dev pkg-config \
          libgdk-pixbuf2.0-dev gperf intltool lzip python3-mako
    - name: Clone MXE
      run: git clone https://github.com/mxe/mxe.git
    - name: Build MXE for Windows targets
      run: |
        cd mxe
        make MXE_TARGETS="i686-w64-mingw32.static x86_64-w64-mingw32.static" -j$(nproc)
    - name: Build libsoundio 32-bit
      run: |
        mkdir build-win32
        cd build-win32
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake
        cmake --build .
    - name: Build libsoundio 64-bit
      run: |
        mkdir build-win64
        cd build-win64
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
        cmake --build .
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          build-win32/*.dll
          build-win32/*.lib
          build-win64/*.dll
          build-win64/*.lib

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install cmake
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/*.dylib

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libasound2-dev libjack-dev libpulse-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/*.so