name: Build libsoundio for Windows/Mac/Linux

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install MXE dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libssl-dev libtool-bin lld lzip make openssl p7zip-full patch perl python3 python3-mako ruby sed unzip wget xz-utils
    - name: Install MXE
      run: |
        git clone https://github.com/mxe/mxe.git
        cd mxe
        make MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static' gcc
        echo "export PATH=$PWD/usr/bin:$PATH" >> $GITHUB_ENV
    - name: Build libsoundio for Windows
      run: |
        mkdir build-win64
        cd build-win64
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
        make
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build-win64/*.dll

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install cmake
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/*.dylib

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libasound2-dev libjack-dev libpulse-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/*.so